Pro2Man.Web/Controllers/API/MachinesController.cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pro2Man.Web.Data;
using Pro2Man.Web.Data.Entities;
using System.Threading.Tasks;

namespace Pro2Man.Web.Controllers.API
{
    [ApiController]
    [Route("api/[controller]")]
    //[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class MachinesController : ControllerBase
    {
        private readonly DataContext _context;

        public MachinesController(DataContext context)
        {
            _context = context;
        }

        [HttpGet("{code}")]
        public async Task<IActionResult> GetMachinesbyCode([FromRoute] string code)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            MachineEntity machineEntity = await _context.Machines.FirstOrDefaultAsync(m => m.CodeMachine == code);

            if (machineEntity == null)
            {
                return NotFound();
            }

            return Ok(machineEntity);
        }
    }
}

Pro2Man.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pro2Man.Web.Models;
using System.Diagnostics;

namespace Pro2Man.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("error/404")]
        public IActionResult Error404()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pro2Man.Web/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pro2Man.Web.Data;
using Pro2Man.Web.Data.Entities;
using Pro2Man.Web.Helpers;
using System.Linq;
using System.Threading.Tasks;

namespace Pro2Man.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReportsController : Controller
    {
        private readonly DataContext _context;
        private readonly IImageHelper _imageHelper;
        private readonly IConverterHelper _converterHelper;

        public ReportsController(
            DataContext context,
            IImageHelper imageHelper,
            IConverterHelper converterHelper)
        {
            _context = context;
            _imageHelper = imageHelper;
            _converterHelper = converterHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Reports
                .Include(t => t.Operator)
                .Include(t => t.Machine)
                .Include(t => t.WorkOrder)
                .OrderBy(t => t.StarReport)
                .ToListAsync());
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ReportEntity reportEntity = await _context.Reports
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reportEntity == null)
            {
                return NotFound();
            }

            _context.Reports.Remove(reportEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ReportEntity reportEntity = await _context.Reports
                .Include(t => t.Operator)
                .Include(t => t.Machine)
                .Include(t => t.WorkOrder)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (reportEntity == null)
            {
                return NotFound();
            }

            return View(reportEntity);
        }

        public async Task<IActionResult> WorkOrder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ReportEntity workOrderEntity = await _context.Reports
                .Include(t => t.WorkOrder)
                .ThenInclude(t => t.Operator)
                .Include(t => t.Machine)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (workOrderEntity == null)
            {
                return NotFound();
            }

            return View(workOrderEntity);
        }
    }
}

Pro2Man.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Pro2Man.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pro2Man.Web/Views/Home/Error404.cshtml
@{
    ViewData["Title"] = "Error404";
}

<br />
<br />
<img src="~/images/LogoPucp.jpg" />
<h2>Página no encontrada</h2>

Pro2Man.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/Carrusel03.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                
            </div>
        </div>
        <div class="item">
            <img src="~/images/Carrusel02.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                
            </div>
        </div>
        <div class="item">
            <img src="~/images/Carrusel01.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="cards-container">
    <div class="card text-center mantenimiento">
        <div class="card-body">
            <img src="https://img.icons8.com/dusk/80/000000/maintenance.png" style="margin-bottom: 1rem;" />
            <h5 class="card-title" style="margin-bottom: 2rem;">Mantenimiento</h5>
            <a href="#" class="btn btn-info btn-lg">Adelante</a>
        </div>
    </div>
    <div class="card text-center reportes">
        <div class="card-body">
            <img src="https://img.icons8.com/dusk/80/000000/report-card.png" style="margin-bottom: 1rem;">
            <h5 class="card-title" style="margin-bottom: 2rem;">Reportes</h5>
            <a a asp-area="" asp-controller="Reports" asp-action="Index" class="btn btn-info btn-lg">Adelante</a>
        </div>
    </div>
    <div class="card text-center maquinas">
        <div class="card-body">
            <img src="https://img.icons8.com/officel/80/000000/Production-machine.png" style="margin-bottom: 1rem;">
            <h5 class="card-title" style="margin-bottom: 2rem;">Máquinas</h5>
            <a asp-area="" asp-controller="Machines" asp-action="Index" class="btn btn-info btn-lg">Adelante</a>
        </div>
    </div>
</div>

<a href="https://icons8.com/icon/79Q1tqI0yvZ3/production-machine"></a>
<a href="https://icons8.com/icon/43171/maintenance"></a>
<a href="https://icons8.com/icon/42942/report-card"></a>